species:
    litura
mainpath:
    /lustre/BIF/nobackup/passa006/thesis_EVE/data/
database:
    /lustre/BIF/nobackup/passa006/thesis_EVE/data/databases/U-RVDBv25.0.fasta
scripts_path:
    /lustre/BIF/nobackup/passa006/thesis_EVE/snakemake/scripts/
database_prot:
    /lustre/BIF/nobackup/passa006/thesis_EVE/data/databases/U-RVDBv25.0-prot.fasta
representative_ref:
    /lustre/BIF/nobackup/passa006/thesis_EVE/data/reference/litura/GCA_002706865.3_ASM270686v3_genomic.fna
reference_path:
    /lustre/BIF/nobackup/passa006/thesis_EVE/data/reference/litura
fastq_files_path:
    /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/

refgenomes:
    GCA_002706865.3_ASM270686v3_genomic.fna: /lustre/BIF/nobackup/passa006/thesis_EVE/data/reference/litura/GCA_002706865.3_ASM270686v3_genomic.fna
    
fastq_names:
    HN5WTDMXX_103943-024-055_ACGTCGTA-GTTCATGG_L002: /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/HN5WTDMXX_103943-024-055_ACGTCGTA-GTTCATGG_L002/HN5WTDMXX_103943-024-055_ACGTCGTA-GTTCATGG_L002
    HFFV2DSXY_103943-023-116_CTCTACTC-GCCACTTA_L002: /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/HFFV2DSXY_103943-023-116_CTCTACTC-GCCACTTA_L002/HFFV2DSXY_103943-023-116_CTCTACTC-GCCACTTA_L002
    HN5WTDMXX_103943-024-049_GCTGTAAG-GCTCTGTA_L002: /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/HN5WTDMXX_103943-024-049_GCTGTAAG-GCTCTGTA_L002/HN5WTDMXX_103943-024-049_GCTGTAAG-GCTCTGTA_L002
    HFFV2DSXY_103943-023-117_CAACCTAG-ACAGACCT_L002: /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/HFFV2DSXY_103943-023-117_CAACCTAG-ACAGACCT_L002/HFFV2DSXY_103943-023-117_CAACCTAG-ACAGACCT_L002
    HN5WTDMXX_103943-024-019_CGGTTGTT-CATACCAC_L002: /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/HN5WTDMXX_103943-024-019_CGGTTGTT-CATACCAC_L002/HN5WTDMXX_103943-024-019_CGGTTGTT-CATACCAC_L002
    HN5WTDMXX_103943-024-058_GATTGGAG-TTCTCTCG_L002: /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/HN5WTDMXX_103943-024-058_GATTGGAG-TTCTCTCG_L002/HN5WTDMXX_103943-024-058_GATTGGAG-TTCTCTCG_L002
    HN5WTDMXX_103943-024-054_GTTAAGGC-TCGAAGGT_L002: /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/HN5WTDMXX_103943-024-054_GTTAAGGC-TCGAAGGT_L002/HN5WTDMXX_103943-024-054_GTTAAGGC-TCGAAGGT_L002
    HN5WTDMXX_103943-024-048_TTCGCAGT-TGATCGGA_L002: /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/HN5WTDMXX_103943-024-048_TTCGCAGT-TGATCGGA_L002/HN5WTDMXX_103943-024-048_TTCGCAGT-TGATCGGA_L002
    HFFV2DSXY_103943-023-139_CTAACTCG-TCGTAGTC_L002: /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/HFFV2DSXY_103943-023-139_CTAACTCG-TCGTAGTC_L002/HFFV2DSXY_103943-023-139_CTAACTCG-TCGTAGTC_L002
    HN5WTDMXX_103943-024-057_ACGGTCTT-TCCGAGTT_L002: /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/HN5WTDMXX_103943-024-057_ACGGTCTT-TCCGAGTT_L002/HN5WTDMXX_103943-024-057_ACGGTCTT-TCCGAGTT_L002
    HN5WTDMXX_103943-024-050_ATTGCGTG-GCCATAAC_L002: /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/HN5WTDMXX_103943-024-050_ATTGCGTG-GCCATAAC_L002/HN5WTDMXX_103943-024-050_ATTGCGTG-GCCATAAC_L002
    HN5WTDMXX_103943-024-053_GATCCATG-TGGAGTTG_L002: /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/HN5WTDMXX_103943-024-053_GATCCATG-TGGAGTTG_L002/HN5WTDMXX_103943-024-053_GATCCATG-TGGAGTTG_L002
    HN5WTDMXX_103943-024-051_TGATACGC-ACTCGTTG_L002: /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/HN5WTDMXX_103943-024-051_TGATACGC-ACTCGTTG_L002/HN5WTDMXX_103943-024-051_TGATACGC-ACTCGTTG_L002
    HFFV2DSXY_103943-023-118_TGATCGGA-TTCGCAGT_L002: /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/HFFV2DSXY_103943-023-118_TGATCGGA-TTCGCAGT_L002/HFFV2DSXY_103943-023-118_TGATCGGA-TTCGCAGT_L002
    HN5WTDMXX_103943-024-056_CTGCGTAT-CGAACTGT_L002: /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/HN5WTDMXX_103943-024-056_CTGCGTAT-CGAACTGT_L002/HN5WTDMXX_103943-024-056_CTGCGTAT-CGAACTGT_L002
    HN5WTDMXX_103943-024-052_CGTCTTGT-TCTCGCAA_L002: /lustre/BIF/nobackup/passa006/thesis_EVE/data/fastq_files/litura/HN5WTDMXX_103943-024-052_CGTCTTGT-TCTCGCAA_L002/HN5WTDMXX_103943-024-052_CGTCTTGT-TCTCGCAA_L002
    