#!/bin/bash

OUTPUTDIRECTORY="/path/to/save/output/"

#Starting  with fa.align file from RepeatMasker
#First cd into directory with .fa.align file

printf "Extracting Kimura divergence scores..."
printf "\n"

#----------------------------------------------------------------------------------------------------------------------
#Extract info from Aag2 genome .fa.align file generated by repeat masker
#----------------------------------------------------------------------------------------------------------------------

#Output both header and kimura score line into one file
grep -e '^Kimura (with divCpGMod)' -e '^[0-9]' Aag2_Contigs.fa.align  > ${OUTPUTDIRECTORY}/bothKimuraScoresAndHeadersFrom_Aag2_Contigs.fa.align.txt

#Extract kimura scores and the line preceding it (alignment header). Because not all alignment headers have a corresponding Kimura score following it. I think this happens with simple repeats.
grep --no-group-separator -B 1 '^Kimura (with divCpGMod)' ${OUTPUTDIRECTORY}/bothKimuraScoresAndHeadersFrom_Aag2_Contigs.fa.align.txt  > ${OUTPUTDIRECTORY}/bothKimuraScoresAndHeaders_filtered_From_Aag2_Contigs.fa.align.txt

#Output only kimura score line
grep '^Kimura (with divCpGMod)' ${OUTPUTDIRECTORY}/bothKimuraScoresAndHeaders_filtered_From_Aag2_Contigs.fa.align.txt  > ${OUTPUTDIRECTORY}/onlyKimuraScores_filtered_From_Aag2_Contigs.fa.align.txt

#Output only header line (ie starts with a number)
grep -e '^[0-9]' ${OUTPUTDIRECTORY}/bothKimuraScoresAndHeaders_filtered_From_Aag2_Contigs.fa.align.txt  > ${OUTPUTDIRECTORY}/onlyHeader_filtered_From_Aag2_Contigs.fa.align.txt

#Check each file has same number of lines
wc -l ${OUTPUTDIRECTORY}/onlyKimuraScores_filtered_From_Aag2_Contigs.fa.align.txt >> ${OUTPUTDIRECTORY}/wcCounts.txt
wc -l ${OUTPUTDIRECTORY}/onlyHeader_filtered_From_Aag2_Contigs.fa.align.txt >> ${OUTPUTDIRECTORY}/wcCounts.txt

